export const GET_ALL_USERS = "GET_ALL_USERS";



export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

/* CART */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QTY = "INCREASE_QTY";
export const DECREASE_QTY = "DECREASE_QTY";
export const CLEAR_CART = "CLEAR_CART";

/* NOTIFICATIONS */
export const GET_NOTIFICATIONS_REQUEST =
  "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS =
  "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE =
  "GET_NOTIFICATIONS_FAILURE";
  export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
  export const MARK_ALL_NOTIFICATIONS_READ =
  "MARK_ALL_NOTIFICATIONS_READ";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";


/* FILTERS */
export const SET_CATEGORY = "SET_CATEGORY";

export const SET_SEARCH = "SET_SEARCH";

export const SET_MIN_PRICE = "SET_MIN_PRICE";

export const SET_MAX_PRICE = "SET_MAX_PRICE";

export const SET_BRAND = "SET_BRAND";

export const SET_COLOR = "SET_COLOR";

export const SET_IN_STOCK = "SET_IN_STOCK";

export const SET_SORT = "SET_SORT";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const UPDATE_CART_STOCK = "UPDATE_CART_STOCK";