export const GET_ALL_USERS = "GET_ALL_USERS";



export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";


/* CART */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QTY = "INCREASE_QTY";
export const DECREASE_QTY = "DECREASE_QTY";
export const CLEAR_CART = "CLEAR_CART";

/* NOTIFICATIONS */
export const GET_NOTIFICATIONS_REQUEST =
  "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS =
  "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE =
  "GET_NOTIFICATIONS_FAILURE";
  export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
  export const MARK_ALL_NOTIFICATIONS_READ =
  "MARK_ALL_NOTIFICATIONS_READ";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";